name: Publish To Npm
on:
  push:
    tags:
      - '*'
jobs:
  test:
    uses: ./.github/workflows/build_and_test.yml

  deploy:
    needs: [test]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use node 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
